// Heritage Studios — Streamlined Services Database Script
// Run: node src/lib/update_services.js

const fs = require('fs');
const path = require('path');

const DB_FILE = path.join(process.cwd(), 'database.json');

function readDb() {
  return JSON.parse(fs.readFileSync(DB_FILE, 'utf8'));
}
function writeDb(data) {
  fs.writeFileSync(DB_FILE, JSON.stringify(data, null, 2), 'utf8');
}

const db = readDb();

// ─────────────────────────────────────────────────────────────
// STREAMLINED SERVICES (6-8 CORE FEATURES PER SERVICE WITH ICONS)
// ─────────────────────────────────────────────────────────────

const enrichedServices = [

  // ══════════════════════════════════════════════
  // 1. CUSTOM WEBSITE DEVELOPMENT
  // ══════════════════════════════════════════════
  {
    id: 'custom-web-development',
    name: 'Custom Website Development',
    slug: 'custom-web-development',
    icon: '💻',
    category: 'Web & E-commerce',
    shortDescription: 'Custom websites, web applications, dashboards, APIs, portals and scalable digital solutions.',
    heroTitle: 'Custom Engineered Website & Web Application Development',
    heroDescription: 'We design and build bespoke, high-performance websites, web apps, SaaS platforms, and custom digital solutions — built for business growth and long-term scalability.',
    startingPrice: 'Starting from PKR 25,000 / $250',
    benefits: [
      'Tailored to your exact brand identity and business goals',
      'Built with modern, scalable frameworks (React, Next.js, Laravel)',
      'Optimised for speed, SEO, and mobile performance',
      'Clean codebase — easy to maintain and extend',
      'Seamlessly integrates with third-party APIs and platforms',
      'Full ownership — source code delivered at project completion',
    ],
    features: [
      { name: 'Custom Website Design', icon: '🎨' },
      { name: 'Full-Stack Web Apps', icon: '💻' },
      { name: 'React & Next.js Stack', icon: '⚛️' },
      { name: 'Laravel & Node.js Backend', icon: '⚙️' },
      { name: 'REST & GraphQL APIs', icon: '🔌' },
      { name: 'Admin Dashboards & Portals', icon: '📊' },
      { name: 'Figma to Clean Code', icon: '📐' },
      { name: 'Speed & Security Hardening', icon: '⚡' },
    ],
    process: [
      'Tell Us Your Requirement — Share your project details, goals, and any existing materials.',
      'We Analyse — We review your requirements, recommend the right stack, and scope the project.',
      'Get Your Quote — You receive a clear proposal with timeline, milestones, and pricing.',
      'We Build & Deliver — Engineering, QA testing, deployment, and final optimisation.',
    ],
    deliverables: [
      'Complete Source Code Repository',
      'Production Deployment (Vercel, AWS, cPanel, or your host)',
      'SEO Setup & Analytics Integration',
      'Post-launch Technical Documentation',
    ],
    technologies: ['React', 'Next.js', 'Node.js', 'Laravel', 'PHP', 'PostgreSQL', 'MySQL', 'Tailwind CSS', 'Figma'],
    pricing: [
      {
        name: 'Starter Website',
        price: 'PKR 25,000–40,000 / $250–400',
        currency: 'PKR/USD',
        billingPeriod: 'one-time',
        description: 'Clean, professional website for small businesses and personal brands.',
        bestFor: 'Small businesses, personal brands, basic professional websites',
        features: [
          'Up to 5 custom pages',
          'Responsive mobile design',
          'Contact form integration',
          'Basic on-page SEO',
          'Google Analytics setup',
          'Fast loading speed',
        ],
        popular: false,
        ctaText: 'Get Started',
        badge: '',
      },
      {
        name: 'Business Website',
        price: 'PKR 45,000–80,000 / $450–800',
        currency: 'PKR/USD',
        billingPeriod: 'one-time',
        description: 'Full corporate website with CMS integration and advanced features.',
        bestFor: 'Growing businesses, agencies, professional companies',
        features: [
          'Up to 12 custom pages',
          'CMS integration',
          'Advanced speed optimisation',
          'Custom contact & enquiry forms',
          'SEO-ready structure',
          'Social media integration',
          '30 days post-launch support',
        ],
        popular: true,
        ctaText: 'Get Started',
        badge: 'Most Popular',
      },
      {
        name: 'Professional Website',
        price: 'PKR 80,000–150,000 / $800–1,500',
        currency: 'PKR/USD',
        billingPeriod: 'one-time',
        description: 'Custom dashboards, portals, and advanced business websites.',
        bestFor: 'Established businesses, advanced websites, custom requirements',
        features: [
          'Unlimited custom pages',
          'Customer portal or admin dashboard',
          'Advanced REST API integrations',
          'Enhanced security setup',
          'Performance & CDN optimisation',
          '60 days post-launch support',
        ],
        popular: false,
        ctaText: 'Get Started',
        badge: '',
      },
      {
        name: 'WooCommerce Store',
        price: 'PKR 70,000–150,000 / $700–1,500',
        currency: 'PKR/USD',
        billingPeriod: 'one-time',
        description: 'Fully functional WooCommerce eCommerce store with payment integration.',
        bestFor: 'Online stores, product businesses, eCommerce brands',
        features: [
          'WooCommerce setup & configuration',
          'Payment gateway integration',
          'Product upload & categorisation',
          'Custom product filters',
          'Cart & checkout customisation',
          'Shipping & tax configuration',
        ],
        popular: false,
        ctaText: 'Build My Store',
        badge: '',
      },
      {
        name: 'Advanced Custom Solution',
        price: 'PKR 150,000+ / $1,500+',
        currency: 'PKR/USD',
        billingPeriod: 'one-time',
        description: 'SaaS platforms, complex web applications, and bespoke corporate solutions.',
        bestFor: 'Custom platforms, advanced functionality, business-specific solutions',
        features: [
          'Bespoke software architecture',
          'Multi-role user systems',
          'Complex third-party integrations',
          'Custom database design',
          'API development & documentation',
          'Long-term support & maintenance',
        ],
        popular: false,
        ctaText: 'Request Custom Quote',
        badge: '',
      },
    ],
    faqs: [
      { question: 'How long does a custom website take to build?', answer: 'A starter website typically takes 1–2 weeks. Business websites take 2–4 weeks. Larger web applications and custom platforms take 4–10 weeks depending on scope.' },
      { question: 'What technologies do you use?', answer: 'We build with React, Next.js, Node.js, Laravel, PHP, PostgreSQL, and MySQL depending on project requirements.' },
      { question: 'Do you work with international clients?', answer: 'Yes. Heritage Studios provides web development services to businesses in Pakistan and worldwide.' },
      { question: 'Are the displayed prices fixed?', answer: 'Displayed prices are starting estimates. Final pricing depends on your specific requirements and functionality.' },
    ],
    audience: ['Small businesses', 'Growing companies', 'Startups', 'Established enterprises', 'eCommerce brands', 'Agencies'],
    whyUs: [
      { title: 'Modern Stack', desc: 'React, Next.js, Node.js & Laravel — fast, clean, scalable.' },
      { title: 'Business-Driven', desc: 'Designed for conversion, clear user journeys, and high performance.' },
      { title: 'Clean Architecture', desc: 'Maintainable code structured for seamless long-term scaling.' },
    ],
    relatedServices: ['wordpress', 'shopify', 'ads-management'],
    crossSell: { serviceId: 'ads-management', message: 'Need to drive traffic to your new website?', ctaText: 'Launch My Ad Campaign', ctaUrl: '/services/ads-management' },
    published: true,
    sortOrder: 1,
    seo: { title: 'Custom Website Development Services | Heritage Studios', description: 'Bespoke custom website development — React, Next.js, Laravel, Node.js. Business websites, web apps, SaaS, portals and eCommerce.' },
  },

  // ══════════════════════════════════════════════
  // 2. WORDPRESS SERVICES
  // ══════════════════════════════════════════════
  {
    id: 'wordpress',
    name: 'WordPress Services',
    slug: 'wordpress',
    icon: '⚡',
    category: 'Web & E-commerce',
    shortDescription: 'WordPress websites, WooCommerce, Elementor, bug fixes, speed optimisation, security, maintenance and custom functionality.',
    heroTitle: 'Professional WordPress Development, Fixes & Maintenance',
    heroDescription: 'From new WordPress website development and WooCommerce stores to urgent bug fixes, speed optimisation, security hardening, and ongoing maintenance — we handle every WordPress requirement.',
    startingPrice: 'Starting from PKR 1,500 / $15',
    benefits: [
      'Covers the full WordPress ecosystem — development, fixes, and maintenance',
      'WooCommerce, Elementor, and custom plugin expertise',
      'Fast turnaround on bug fixes and critical errors',
      'Security-first approach to every WordPress project',
      'Affordable monthly maintenance to keep your site running',
    ],
    features: [
      { name: 'Business WordPress Sites', icon: '🌐' },
      { name: 'WooCommerce Store Setup', icon: '🛒' },
      { name: 'Elementor & Custom Layouts', icon: '🎨' },
      { name: 'Bug & Critical Error Fixes', icon: '🛠️' },
      { name: 'Speed & Core Web Vitals', icon: '⚡' },
      { name: 'Security & Malware Removal', icon: '🔒' },
      { name: 'Custom Plugins & Themes', icon: '🧩' },
      { name: 'Monthly Maintenance Plans', icon: '🛡️' },
    ],
    process: [
      'Tell Us Your Requirement — Describe your WordPress issue, project, or maintenance need.',
      'We Analyse — We review your site, diagnose the issue, or scope your project.',
      'Get Your Quote — Clear pricing for your specific requirement.',
      'We Fix, Build or Maintain — Fast, professional delivery with full testing.',
    ],
    deliverables: [
      'Fixed / Developed WordPress website',
      'Testing confirmation report',
      'Documentation for custom work',
    ],
    technologies: ['WordPress', 'WooCommerce', 'Elementor', 'PHP', 'MySQL', 'JavaScript', 'CSS'],
    bugFixPricing: [
      { name: 'Minor WordPress Fix', price: 'PKR 1,500–3,000 / $15–30', description: 'Small text changes, minor layout tweaks, simple settings adjustments.' },
      { name: 'WordPress Bug / Error Fix', price: 'PKR 3,000–7,000 / $30–70', description: 'Plugin conflicts, theme errors, login issues, general WordPress errors.' },
      { name: 'Elementor Fix', price: 'PKR 2,500–6,000 / $25–60', description: 'Elementor layout issues, broken sections, widget errors, design fixes.' },
      { name: 'WooCommerce Fix', price: 'PKR 4,000–10,000 / $40–100', description: 'Cart issues, checkout errors, payment gateway problems, product display errors.' },
      { name: 'Critical Website Error', price: 'PKR 7,000–15,000 / $70–150', description: 'White screen, Error 500, site completely down, critical functionality broken.' },
      { name: 'Malware Removal', price: 'PKR 8,000–20,000 / $80–200', description: 'Full malware scan, removal, security hardening, and monitoring setup.' },
    ],
    bugFixDisclaimer: 'Final price depends on issue complexity. A diagnosis is performed before confirming the exact price.',
    pricing: [
      {
        name: 'Basic Maintenance',
        price: '$49/month',
        currency: 'USD',
        billingPeriod: 'monthly',
        startingFromPkr: 'Starting from PKR 5,000/month',
        description: 'Essential monthly maintenance to keep your WordPress site secure and up to date.',
        bestFor: 'Small websites with minimal changes',
        features: [
          'WordPress core updates',
          'Plugin & theme updates',
          'Weekly backups',
          'Security monitoring',
          'Minor bug fixes (up to 1 hour/month)',
          'Monthly health report',
        ],
        popular: false,
        ctaText: 'Choose Basic',
        badge: '',
      },
      {
        name: 'Business Maintenance',
        price: '$99/month',
        currency: 'USD',
        billingPeriod: 'monthly',
        startingFromPkr: 'Starting from PKR 10,000/month',
        description: 'Comprehensive monthly maintenance with speed monitoring, security, and content updates.',
        bestFor: 'Business websites with regular activity',
        features: [
          'Everything in Basic',
          'Speed & performance monitoring',
          'Advanced security monitoring',
          'Technical bug fixes (up to 3 hours/month)',
          'Content & product updates',
          'Priority email support',
        ],
        popular: true,
        ctaText: 'Choose Business',
        badge: 'Most Popular',
      },
      {
        name: 'Premium Maintenance',
        price: '$199/month',
        currency: 'USD',
        billingPeriod: 'monthly',
        startingFromPkr: 'Starting from PKR 20,000/month',
        description: 'Full-service WordPress management with priority support and advanced optimisation.',
        bestFor: 'High-traffic sites, WooCommerce stores',
        features: [
          'Everything in Business',
          'Priority support (faster response)',
          'Advanced performance optimisation',
          'WooCommerce product & order support',
          'Larger monthly task allocation',
          'Security audit every 3 months',
        ],
        popular: false,
        ctaText: 'Choose Premium',
        badge: '',
      },
    ],
    faqs: [
      { question: 'Can you fix an existing WordPress website?', answer: 'Yes. We fix bugs, errors, broken layouts, plugin conflicts, WooCommerce issues, and more.' },
      { question: 'Do you work with WooCommerce?', answer: 'Yes. We develop, customise, and fix WooCommerce stores including payment gateways and checkout.' },
      { question: 'How quickly can you fix my WordPress error?', answer: 'Most minor fixes are completed within 24–48 hours.' },
    ],
    relatedServices: ['custom-web-development', 'shopify', 'ads-management'],
    crossSell: { serviceId: 'ads-management', message: 'Need leads from your WordPress website?', ctaText: 'Launch My Ad Campaign', ctaUrl: '/services/ads-management' },
    published: true,
    sortOrder: 2,
    seo: { title: 'WordPress Services — Development, Bug Fixes & Maintenance | Heritage Studios', description: 'WordPress development, WooCommerce, Elementor, bug fixes, speed optimisation, security, and monthly maintenance.' },
  },

  // ══════════════════════════════════════════════
  // 3. SHOPIFY SERVICES
  // ══════════════════════════════════════════════
  {
    id: 'shopify',
    name: 'Shopify Services',
    slug: 'shopify',
    icon: '🛍️',
    category: 'Web & E-commerce',
    shortDescription: 'Shopify store development, customisation, Liquid development, integrations, optimisation and eCommerce solutions.',
    heroTitle: 'Professional Shopify Store Development & Customisation',
    heroDescription: 'Build, customise, and optimise your Shopify store with expert Liquid development, conversion-focused design, and eCommerce solutions tailored for growth.',
    startingPrice: 'Starting from PKR 2,000 / $20',
    benefits: [
      'Expert Shopify Liquid development for full theme control',
      'Conversion-focused store design and UX',
      'Fast, mobile-first Shopify storefronts',
      'Seamless app integrations and third-party tools',
      'Fast turnaround on bug fixes and critical errors',
    ],
    features: [
      { name: 'Custom Shopify Store Setup', icon: '🛒' },
      { name: 'Shopify 2.0 Theme Customisation', icon: '🎨' },
      { name: 'Liquid Code & Custom Sections', icon: '⚙️' },
      { name: 'Bug, Cart & Checkout Fixes', icon: '🛠️' },
      { name: 'Payment & Shipping Gateway', icon: '💳' },
      { name: 'App & Analytics Integration', icon: '🔌' },
      { name: 'Speed & Core Web Vitals', icon: '⚡' },
      { name: 'Migration to Shopify', icon: '📦' },
    ],
    process: [
      'Tell Us Your Requirement — Share your Shopify project, issue, or store details.',
      'We Analyse — We review your store, diagnose the problem, or scope your project.',
      'Get Your Quote — Clear pricing for your specific requirement.',
      'We Build, Fix or Optimise — Professional delivery with full testing before handoff.',
    ],
    deliverables: [
      'Completed Shopify store or customisation',
      'Testing confirmation',
      'App configuration notes',
    ],
    technologies: ['Shopify Liquid', 'JavaScript', 'CSS', 'HTML', 'Shopify API', 'Shopify 2.0'],
    bugFixPricing: [
      { name: 'Minor Shopify Fix', price: 'PKR 2,000–4,000 / $20–40', description: 'Small text or layout changes, minor settings adjustments.' },
      { name: 'Shopify Bug Fix', price: 'PKR 3,000–8,000 / $30–80', description: 'App conflicts, theme errors, broken functionality.' },
      { name: 'Liquid Fix', price: 'PKR 4,000–10,000 / $40–100', description: 'Liquid template errors, broken sections, custom Liquid issues.' },
      { name: 'Theme Issue', price: 'PKR 4,000–10,000 / $40–100', description: 'Theme display issues, broken sections, theme update conflicts.' },
      { name: 'Checkout Issue', price: 'PKR 5,000–15,000 / $50–150', description: 'Checkout errors, payment issues, cart problems.' },
      { name: 'Critical Shopify Issue', price: 'PKR 8,000–20,000 / $80–200', description: 'Store completely broken, critical payment failure.' },
    ],
    bugFixDisclaimer: 'Final price depends on issue complexity. A diagnosis is performed before confirming the exact price.',
    pricing: [
      {
        name: 'Shopify Store Setup',
        price: 'PKR 30,000–70,000 / $300–700',
        currency: 'PKR/USD',
        billingPeriod: 'one-time',
        description: 'Complete Shopify store setup with theme customisation and product upload.',
        bestFor: 'New eCommerce businesses, dropshipping stores',
        features: [
          'Shopify store configuration',
          'Theme installation & customisation',
          'Up to 20 products uploaded',
          'Payment & shipping setup',
          'Mobile responsive design',
        ],
        popular: true,
        ctaText: 'Build My Store',
        badge: 'Most Popular',
      },
      {
        name: 'Custom Shopify Store',
        price: 'PKR 80,000–180,000 / $800–1,800',
        currency: 'PKR/USD',
        billingPeriod: 'one-time',
        description: 'Fully custom Liquid store with custom sections, app integrations, and conversion UX.',
        bestFor: 'Established brands, custom storefront requirements',
        features: [
          'Bespoke Liquid theme development',
          'Custom section & page templates',
          'Advanced app & pixel integrations',
          'Custom product options & bundles',
          'Speed & SEO optimisation',
        ],
        popular: false,
        ctaText: 'Build Custom Store',
        badge: '',
      },
    ],
    faqs: [
      { question: 'Can you build a custom Liquid section?', answer: 'Yes. We build custom Liquid sections, page templates, and product layouts tailored to your exact store design.' },
      { question: 'Do you fix broken Shopify themes?', answer: 'Yes. We diagnose and fix theme display errors, Liquid bugs, broken carts, and app conflicts.' },
    ],
    relatedServices: ['ads-management', 'video-editing', 'custom-web-development'],
    crossSell: { serviceId: 'ads-management', message: 'Ready to drive sales to your Shopify store?', ctaText: 'Grow My Store With Ads', ctaUrl: '/services/ads-management' },
    published: true,
    sortOrder: 3,
    seo: { title: 'Shopify Store Development & Customisation | Heritage Studios', description: 'Shopify store development, custom Liquid coding, theme customisation, bug fixes, speed optimisation, and migration.' },
  },

  // ══════════════════════════════════════════════
  // 4. PAID ADVERTISING & ADS MANAGEMENT
  // ══════════════════════════════════════════════
  {
    id: 'ads-management',
    name: 'Paid Advertising & Marketing',
    slug: 'ads-management',
    icon: '📈',
    category: 'Software & Technology',
    shortDescription: 'Meta, Google, TikTok, YouTube ads, retargeting, lead generation, tracking and campaign management.',
    heroTitle: 'Data-Driven Paid Advertising & Performance Marketing',
    heroDescription: 'Scale your business with strategic paid advertising campaigns across Meta (Facebook & Instagram), Google, TikTok, and YouTube — engineered for measurable growth.',
    startingPrice: 'Starting from $49 (Audit) / $199/month',
    benefits: [
      'Multi-platform expertise: Meta, Google, TikTok, YouTube',
      'Data-driven campaign setup and structure',
      'Advanced audience research and targeting',
      'Custom conversion tracking & Meta CAPI setup',
      'Regular optimization and transparent reporting',
    ],
    features: [
      { name: 'Meta Ads (FB & Insta)', icon: '📱' },
      { name: 'Google Ads & PPC Search', icon: '🔍' },
      { name: 'TikTok Ads & Video Campaigns', icon: '🎵' },
      { name: 'Retargeting & Funnel Setup', icon: '🔄' },
      { name: 'eCommerce & Lead Generation', icon: '💼' },
      { name: 'Conversion Tracking & CAPI', icon: '🎯' },
      { name: 'Ad Creative Strategy', icon: '🎨' },
      { name: 'Ads Account Audits ($49)', icon: '📊' },
    ],
    process: [
      'Tell Us Your Objective — Share your business goals, target audience, and ad budget.',
      'Strategy & Funnel Audit — We research your market, competitors, and audience.',
      'Campaign Build & Tracking — We set up account structure, pixel/CAPI, and campaigns.',
      'Optimize & Scale — Ongoing A/B testing, budget management, and monthly reports.',
    ],
    deliverables: [
      'Fully structured ad campaigns',
      'Conversion tracking configuration',
      'Monthly performance report & strategy call',
    ],
    technologies: ['Meta Ads Manager', 'Google Ads', 'TikTok Ads Manager', 'Google Tag Manager', 'GA4', 'Meta CAPI'],
    adsDisclaimer: 'Management fees do not include advertising spend. Ad spend is paid directly to Meta/Google.',
    adsSpendExample: 'Example: If your ad budget is $1,000/mo, that $1,000 goes to Meta. Our management fee is separate based on plan.',
    adsAudit: {
      startingPrice: '$49',
      startingPricePkr: 'Starting from PKR 12,500',
      includes: [
        'Campaign Structure & Settings Audit',
        'Audience Targeting & Segment Analysis',
        'Ad Creative & Copy Assessment',
        'Pixel, CAPI & Conversion Tracking Check',
        'Budget Waste Identification',
        'Actionable Optimization Action Plan',
      ],
    },
    pricing: [
      {
        name: 'Starter Plan',
        price: '$199/month',
        currency: 'USD',
        billingPeriod: 'monthly',
        startingFromPkr: 'Starting from PKR 25,000/month',
        description: 'Ideal for small businesses getting started with paid advertising on 1 platform.',
        bestFor: 'Small businesses, single platform focus',
        features: [
          '1 Advertising Platform (Meta or Google)',
          'Campaign setup & audience targeting',
          'Up to 3 ad sets / 6 ad creatives',
          'Conversion tracking setup',
          'Weekly optimization',
          'Monthly performance report',
        ],
        popular: false,
        ctaText: 'Choose Starter',
        badge: '',
      },
      {
        name: 'Growth Plan',
        price: '$399/month',
        currency: 'USD',
        billingPeriod: 'monthly',
        startingFromPkr: 'Starting from PKR 50,000/month',
        description: 'Comprehensive multi-platform campaign management with retargeting & funnel testing.',
        bestFor: 'Growing eCommerce stores, active lead generation',
        features: [
          'Up to 2 Platforms (Meta + Google or TikTok)',
          'Advanced audience testing & retargeting',
          'Creative testing & copy optimization',
          'Meta CAPI & GA4 conversion setup',
          'Bi-weekly optimizations',
          'Detailed monthly analytics report',
        ],
        popular: true,
        ctaText: 'Choose Growth',
        badge: 'Most Popular',
      },
      {
        name: 'Performance Plan',
        price: '$799/month',
        currency: 'USD',
        billingPeriod: 'monthly',
        startingFromPkr: 'Starting from PKR 100,000/month',
        description: 'Full-scale performance advertising across multiple channels for scaling brands.',
        bestFor: 'Scaling brands, high ad spend, multi-channel strategy',
        features: [
          'Multi-Platform Management (Meta, Google, TikTok, YT)',
          'Advanced funnel & retargeting strategy',
          'Continuous creative & landing page testing',
          'Conversion rate recommendations',
          'Priority support & weekly updates',
        ],
        popular: false,
        ctaText: 'Choose Performance',
        badge: '',
      },
    ],
    oneTimeSetup: [
      { name: 'Basic Campaign Setup', price: 'PKR 10,000–20,000 / $100–200', features: ['Account setup', '1 Campaign structure', 'Targeting setup', 'Basic pixel check'] },
      { name: 'Professional Campaign Setup', price: 'PKR 25,000–50,000 / $250–500', features: ['Full strategy', 'Audience research', 'Funnel & retargeting setup', 'CAPI & GTM setup'] },
    ],
    faqs: [
      { question: 'Does your management fee include ad spend?', answer: 'No. Management fees cover our strategy, setup, and optimization services. Your ad budget is paid directly to Meta, Google, or TikTok.' },
      { question: 'Do you guarantee sales or ROI?', answer: 'No. We focus on data-driven campaigns and conversion optimization, but performance depends on product offer, market demand, website UX, and pricing.' },
    ],
    relatedServices: ['video-editing', 'shopify', 'custom-web-development'],
    crossSell: { serviceId: 'video-editing', message: 'Need high-converting video ads for your campaigns?', ctaText: 'Create Video Ads', ctaUrl: '/services/video-editing' },
    published: true,
    sortOrder: 4,
    seo: { title: 'Paid Advertising & Marketing Services | Heritage Studios', description: 'Meta Ads, Google Ads, TikTok Ads, retargeting, lead generation, conversion tracking, and performance marketing.' },
  },

  // ══════════════════════════════════════════════
  // 5. VIDEO EDITING & DIGITAL MEDIA
  // ══════════════════════════════════════════════
  {
    id: 'video-editing',
    name: 'Video Editing & Digital Media',
    slug: 'video-editing',
    icon: '🎬',
    category: 'Creative',
    shortDescription: 'Reels, YouTube videos, ads, corporate videos, motion graphics, VFX, 3D, audio and post-production.',
    heroTitle: 'Professional Post-Production & Video Editing',
    heroDescription: 'High-retention video editing, motion graphics, social media Reels, YouTube content, and high-converting video ads tailored for brands.',
    startingPrice: 'Starting from $499 (Shorts Pack) / Custom Quote',
    benefits: [
      'High-retention editing techniques that keep viewers watching',
      'Dynamic captions, sound effects, and color grading',
      'Custom motion graphics, logo reveals, and lower thirds',
      'Optimised formats for Reels, Shorts, TikTok, and YouTube',
      'Professional post-production team with fast turnaround',
    ],
    features: [
      { name: 'Instagram Reels & TikTok Clips', icon: '📱' },
      { name: 'YouTube Long-form & Vlogs', icon: '▶️' },
      { name: 'High-Converting Video Ads', icon: '🎯' },
      { name: 'Motion Graphics & Text VFX', icon: '✨' },
      { name: '3D Product Animation', icon: '📦' },
      { name: 'Color Grading & Sound Design', icon: '🎨' },
      { name: 'Podcast Video & Audio Cleanup', icon: '🎙️' },
      { name: 'Corporate & Brand Videos', icon: '🏢' },
    ],
    process: [
      'Submit Your Footage — Send raw footage, brand guidelines, and reference styles.',
      'We Review & Edit — Our editors cut, format, add motion graphics, and refine audio.',
      'Review Rough Cut — You receive a preview link to review and request revisions.',
      'Final Handoff — High-resolution exports delivered in all required aspect ratios.',
    ],
    deliverables: [
      'High-resolution MP4/MOV exports',
      'Formatted for desktop, vertical Reels/TikTok, and square formats',
      'SRT subtitle files upon request',
    ],
    technologies: ['Premiere Pro', 'After Effects', 'DaVinci Resolve', 'Blender', 'Audition'],
    pricingDisclaimer: 'Pricing depends on video duration, raw footage amount, editing complexity, motion graphics, 3D elements, and turnaround time.',
    pricing: [
      {
        name: 'Shorts & Reels Pack',
        price: '$499 / PKR 50,000',
        currency: 'USD/PKR',
        billingPeriod: 'project',
        description: 'Pack of 10 short-form vertical videos edited for maximum retention.',
        bestFor: 'Creators, influencers, brands building social presence',
        features: [
          '10 Short-form videos (up to 60s each)',
          'Dynamic captions & subtitles',
          'Sound design & background music',
          'Color correction & zooms',
          '1 Revision per video',
        ],
        popular: true,
        ctaText: 'Order Shorts Pack',
        badge: 'Popular Pack',
      },
      {
        name: 'YouTube & Long-form Editing',
        price: 'Custom Quote',
        currency: 'USD/PKR',
        billingPeriod: 'per video / monthly',
        description: 'Professional long-form video editing with B-roll, motion graphics, and audio mastering.',
        bestFor: 'YouTube channels, podcasts, tutorials',
        features: [
          'Full pacing & narrative cuts',
          'B-roll insertion & screen recordings',
          'Custom lower thirds & titles',
          'Audio noise reduction & mastering',
          'Thumbnail suggestions',
        ],
        popular: false,
        ctaText: 'Request Custom Quote',
        badge: '',
      },
      {
        name: 'Video Ad Production',
        price: 'Custom Quote',
        currency: 'USD/PKR',
        billingPeriod: 'per ad',
        description: 'High-converting eCommerce and brand video ads for Meta, TikTok, and YouTube.',
        bestFor: 'eCommerce brands, performance campaigns',
        features: [
          'Hook variation testing',
          'Dynamic text overlays & CTA callouts',
          'Licensed background music',
          'Multiple aspect ratio exports (9:16, 1:1, 16:9)',
        ],
        popular: false,
        ctaText: 'Request Custom Quote',
        badge: '',
      },
    ],
    faqs: [
      { question: 'How is video editing priced?', answer: 'Pricing depends on video length, raw footage quantity, motion graphics complexity, color grading, sound design, and turnaround time.' },
      { question: 'Do you offer monthly editing retainer plans?', answer: 'Yes. We offer recurring monthly retainers for YouTube channels, social media creators, and eCommerce ad creative production.' },
    ],
    relatedServices: ['ads-management', 'shopify', 'custom-web-development'],
    crossSell: { serviceId: 'ads-management', message: 'Turn your video edits into high-converting ad campaigns.', ctaText: 'Launch Ad Campaign', ctaUrl: '/services/ads-management' },
    published: true,
    sortOrder: 5,
    seo: { title: 'Professional Video Editing Services | Heritage Studios', description: 'Video editing services — Reels, TikTok, YouTube videos, video ads, motion graphics, 3D animation, and audio post-production.' },
  },

  // ══════════════════════════════════════════════
  // SUB-SERVICES (Parented under families)
  // ══════════════════════════════════════════════

  // 6. WordPress Development
  {
    id: 'wordpress-development',
    name: 'WordPress Website Development',
    slug: 'wordpress-development',
    parentService: 'wordpress',
    icon: '🌐',
    category: 'Web & E-commerce',
    shortDescription: 'Custom WordPress website development, Elementor builds, WooCommerce, and theme customisation.',
    heroTitle: 'Custom WordPress Website Development',
    heroDescription: 'Bespoke WordPress websites built with clean code, Elementor Pro, and custom themes tailored for business outcomes.',
    startingPrice: 'Starting from PKR 25,000 / $250',
    benefits: ['Mobile responsive design', 'Easy to manage dashboard', 'SEO-friendly structure'],
    features: [
      { name: 'Business & Corporate Sites', icon: '🏢' },
      { name: 'WooCommerce Store Setup', icon: '🛒' },
      { name: 'Elementor Pro Customisation', icon: '🎨' },
      { name: 'PSD/Figma to WordPress', icon: '📐' },
      { name: 'Custom Plugin Integration', icon: '🔌' },
      { name: 'Speed & Security Setup', icon: '⚡' },
    ],
    pricing: [
      { name: 'Starter WordPress', price: 'PKR 25,000–40,000 / $250–400', currency: 'PKR/USD', description: 'Up to 5 custom pages.', features: ['Responsive design', 'Contact form', 'Basic SEO'], ctaText: 'Get Started' },
      { name: 'Business WordPress', price: 'PKR 45,000–80,000 / $450–800', currency: 'PKR/USD', description: 'Corporate site with custom sections.', features: ['Up to 12 pages', 'Speed optimization', '30 days support'], popular: true, ctaText: 'Get Started', badge: 'Most Popular' },
    ],
    published: true,
    sortOrder: 6,
  },

  // 7. WordPress Fixes
  {
    id: 'wordpress-fixes',
    name: 'WordPress Bug & Error Fixes',
    slug: 'wordpress-fixes',
    parentService: 'wordpress',
    icon: '🛠️',
    category: 'Web & E-commerce',
    shortDescription: 'Urgent WordPress bug fixes, white screen of death, plugin conflicts, and layout repair.',
    heroTitle: 'Fast WordPress Bug & Error Fixing Services',
    heroDescription: 'Diagnose and repair WordPress critical errors, plugin conflicts, layout issues, and WooCommerce failures quickly.',
    startingPrice: 'Starting from PKR 1,500 / $15',
    benefits: ['Fast 24-48h turnaround', 'Diagnosis before charge', 'Full backup before fixing'],
    features: [
      { name: 'White Screen of Death Fix', icon: '⚪' },
      { name: 'Plugin & Theme Conflict Fix', icon: '🧩' },
      { name: 'Elementor Layout Fix', icon: '📐' },
      { name: 'WooCommerce Checkout Fix', icon: '💳' },
      { name: 'Database & PHP Error Fix', icon: '⚙️' },
      { name: 'Malware Cleanup & Audit', icon: '🔒' },
    ],
    bugFixPricing: [
      { name: 'Minor Fix', price: 'PKR 1,500–3,000 / $15–30', description: 'Small layout tweak or minor settings fix.' },
      { name: 'Critical Error Fix', price: 'PKR 7,000–15,000 / $70–150', description: 'White screen or site down emergency fix.' },
    ],
    bugFixDisclaimer: 'Exact price is confirmed after initial diagnosis.',
    published: true,
    sortOrder: 7,
  },

  // 8. WordPress Maintenance
  {
    id: 'wordpress-maintenance',
    name: 'WordPress Maintenance & Security',
    slug: 'wordpress-maintenance',
    parentService: 'wordpress',
    icon: '🛡️',
    category: 'Web & E-commerce',
    shortDescription: 'Monthly WordPress maintenance, updates, backups, security monitoring, and speed tuning.',
    heroTitle: 'Ongoing WordPress Maintenance & Care Plans',
    heroDescription: 'Keep your WordPress website safe, updated, fast, and issue-free with dedicated monthly maintenance.',
    startingPrice: 'Starting from $49/month',
    benefits: ['Weekly offsite backups', 'Security monitoring', 'Peace of mind'],
    features: [
      { name: 'Core & Plugin Updates', icon: '🔄' },
      { name: 'Weekly Offsite Backups', icon: '💾' },
      { name: '24/7 Security Uptime Check', icon: '🛡️' },
      { name: 'Speed Optimisation', icon: '⚡' },
      { name: 'Technical Bug Fix Allowance', icon: '🛠️' },
      { name: 'Monthly Health Report', icon: '📊' },
    ],
    pricing: [
      { name: 'Basic Care', price: '$49/month', currency: 'USD', description: 'Essential updates and backups.', features: ['Updates', 'Weekly backups', 'Minor fixes'], ctaText: 'Choose Basic' },
      { name: 'Business Care', price: '$99/month', currency: 'USD', description: 'Full performance and security management.', features: ['Everything in Basic', 'Speed monitoring', '3h task time'], popular: true, ctaText: 'Choose Business', badge: 'Most Popular' },
    ],
    published: true,
    sortOrder: 8,
  },

  // 9. Shopify Store Development
  {
    id: 'shopify-store-development',
    name: 'Shopify Store Development',
    slug: 'shopify-store-development',
    parentService: 'shopify',
    icon: '🛒',
    category: 'Web & E-commerce',
    shortDescription: 'Complete Shopify online store design, setup, theme customisation, and launch.',
    heroTitle: 'High-Converting Shopify Store Development',
    heroDescription: 'Launch a high-converting Shopify store designed for sales, seamless navigation, and mobile buyers.',
    startingPrice: 'Starting from PKR 30,000 / $300',
    benefits: ['Conversion UX design', 'Mobile-first layout', 'Payment gateway setup'],
    features: [
      { name: 'Full Store Setup', icon: '🏬' },
      { name: 'Theme Customisation', icon: '🎨' },
      { name: 'Product Upload & Category', icon: '📦' },
      { name: 'Payment & Tax Setup', icon: '💳' },
      { name: 'Mobile UX Optimisation', icon: '📱' },
      { name: 'Domain & Launch Handoff', icon: '🚀' },
    ],
    pricing: [
      { name: 'Shopify Setup', price: 'PKR 30,000–70,000 / $300–700', currency: 'PKR/USD', description: 'Complete store build.', features: ['Store config', 'Up to 20 products', 'Payment setup'], popular: true, ctaText: 'Build My Store', badge: 'Most Popular' },
    ],
    published: true,
    sortOrder: 9,
  },

  // 10. Shopify Customization & Liquid
  {
    id: 'shopify-customization',
    name: 'Shopify Customisation & Liquid',
    slug: 'shopify-customization',
    parentService: 'shopify',
    icon: '🎨',
    category: 'Web & E-commerce',
    shortDescription: 'Custom Shopify Liquid coding, custom sections, page templates, and app integrations.',
    heroTitle: 'Custom Shopify Liquid & Theme Customisation',
    heroDescription: 'Tailor your Shopify theme with custom Liquid code, dynamic sections, and bespoke cart features.',
    startingPrice: 'Starting from PKR 4,000 / $40',
    benefits: ['Tailored section layout', 'No bloat Liquid code', 'Unique brand experience'],
    features: [
      { name: 'Custom Liquid Sections', icon: '⚙️' },
      { name: 'Custom Cart & Drawer UX', icon: '🛍️' },
      { name: 'Product Bundles & Options', icon: '📦' },
      { name: 'Mega Menu & Header Design', icon: '📌' },
      { name: 'Custom Fonts & CSS Styling', icon: '🎨' },
      { name: 'App & Analytics Tracking', icon: '📊' },
    ],
    published: true,
    sortOrder: 10,
  },

  // 11. Shopify Bug Fixes
  {
    id: 'shopify-bug-fixes',
    name: 'Shopify Bug & Error Fixes',
    slug: 'shopify-bug-fixes',
    parentService: 'shopify',
    icon: '🔧',
    category: 'Web & E-commerce',
    shortDescription: 'Fast fix for broken Shopify themes, Liquid errors, cart failures, and app conflicts.',
    heroTitle: 'Shopify Bug & Theme Repair Services',
    heroDescription: 'Fast diagnosis and repair of broken Shopify sections, Liquid template errors, and checkout issues.',
    startingPrice: 'Starting from PKR 2,000 / $20',
    benefits: ['Fast turnaround', 'Diagnosis before charge', 'Zero downtime fix'],
    features: [
      { name: 'Liquid Code Repair', icon: '💻' },
      { name: 'Theme Display Fix', icon: '🎨' },
      { name: 'Cart & Checkout Error Fix', icon: '🛒' },
      { name: 'App Conflict Resolution', icon: '🔌' },
      { name: 'Mobile Layout Fix', icon: '📱' },
    ],
    bugFixPricing: [
      { name: 'Minor Fix', price: 'PKR 2,000–4,000 / $20–40', description: 'Small layout or settings adjustment.' },
      { name: 'Theme / Liquid Fix', price: 'PKR 4,000–10,000 / $40–100', description: 'Liquid template or broken layout fix.' },
    ],
    published: true,
    sortOrder: 11,
  },

  // 12. Meta Ads Management
  {
    id: 'meta-ads',
    name: 'Meta Ads (Facebook & Instagram)',
    slug: 'meta-ads',
    parentService: 'ads-management',
    icon: '🎯',
    category: 'Software & Technology',
    shortDescription: 'Targeted Facebook & Instagram ad campaigns focused on leads, sales, and brand growth.',
    heroTitle: 'Meta Ads Management (Facebook & Instagram)',
    heroDescription: 'Drive targeted traffic, sales, and qualified leads with strategic Facebook & Instagram advertising.',
    startingPrice: 'Starting from $199/month',
    benefits: ['Targeted audience funnels', 'Pixel & CAPI tracking', 'Creative testing'],
    features: [
      { name: 'Campaign Setup & Strategy', icon: '📊' },
      { name: 'Lookalike & Custom Audiences', icon: '👥' },
      { name: 'Retargeting Funnels', icon: '🔄' },
      { name: 'Meta CAPI & Pixel Setup', icon: '🎯' },
      { name: 'Ad Copy & Creative Direction', icon: '🎨' },
      { name: 'Weekly Optimisation', icon: '⚡' },
    ],
    pricing: [
      { name: 'Meta Starter', price: '$199/month', currency: 'USD', description: 'Full Facebook & Instagram campaign management.', features: ['Campaign setup', 'Audience research', 'Weekly optimization'], popular: true, ctaText: 'Choose Starter', badge: 'Most Popular' },
    ],
    published: true,
    sortOrder: 12,
  },

  // 13. Google Ads Management
  {
    id: 'google-ads',
    name: 'Google Ads & Search PPC',
    slug: 'google-ads',
    parentService: 'ads-management',
    icon: '🔍',
    category: 'Software & Technology',
    shortDescription: 'Google Search PPC, Shopping, and Display campaigns for high-intent customer acquisition.',
    heroTitle: 'Google Ads & PPC Search Campaign Management',
    heroDescription: 'Capture high-intent searchers actively looking for your products and services on Google.',
    startingPrice: 'Starting from $199/month',
    benefits: ['High-intent traffic', 'Keyword research & negative keywords', 'Conversion tracking'],
    features: [
      { name: 'Google Search PPC', icon: '🔍' },
      { name: 'Google Shopping Ads', icon: '🛒' },
      { name: 'Keyword & Negative Match', icon: '🔑' },
      { name: 'Conversion & GA4 Tracking', icon: '📊' },
      { name: 'Ad Copywriting & Extensions', icon: '✍️' },
      { name: 'Bid & Budget Optimisation', icon: '💰' },
    ],
    published: true,
    sortOrder: 13,
  },

  // 14. Instagram Reels & Short Form Editing
  {
    id: 'reels-editing',
    name: 'Instagram Reels & Short-Form Editing',
    slug: 'reels-editing',
    parentService: 'video-editing',
    icon: '📱',
    category: 'Creative',
    shortDescription: 'High-retention editing for Instagram Reels, TikToks, and YouTube Shorts with dynamic captions.',
    heroTitle: 'Instagram Reels & Short-Form Video Editing',
    heroDescription: 'Turn raw clips into viral, high-retention Reels, Shorts, and TikToks with dynamic captions and FX.',
    startingPrice: 'Starting from $499 (10-Pack)',
    benefits: ['Fast cuts & high retention', 'Animated captions', 'Sound effects'],
    features: [
      { name: 'Dynamic Captions & Subtitles', icon: '📝' },
      { name: 'Fast Cuts & Zoom FX', icon: '⚡' },
      { name: 'Sound Design & Foley', icon: '🔊' },
      { name: 'Trending Audio Sync', icon: '🎵' },
      { name: 'Color Correction', icon: '🎨' },
    ],
    pricing: [
      { name: 'Reels 10-Pack', price: '$499 / PKR 50,000', currency: 'USD/PKR', description: '10 High-retention short-form edits.', features: ['10 Videos', 'Dynamic captions', 'Sound FX'], popular: true, ctaText: 'Order Pack', badge: 'Popular Pack' },
    ],
    published: true,
    sortOrder: 14,
  },

  // 15. YouTube Video Editing
  {
    id: 'youtube-editing',
    name: 'YouTube & Long-Form Video Editing',
    slug: 'youtube-editing',
    parentService: 'video-editing',
    icon: '▶️',
    category: 'Creative',
    shortDescription: 'Long-form YouTube video editing, podcasts, talking-head videos, and documentary cuts.',
    heroTitle: 'YouTube & Long-Form Video Post-Production',
    heroDescription: 'Professional editing for YouTube channels, podcasts, and video series with B-roll and audio mastering.',
    startingPrice: 'Custom Quote',
    benefits: ['Pacing for watch time', 'Clean audio mastering', 'Custom graphics'],
    features: [
      { name: 'Narrative & Pacing Cuts', icon: '🎬' },
      { name: 'B-Roll Insertion', icon: '📹' },
      { name: 'Custom Lower Thirds & Titles', icon: '🎨' },
      { name: 'Audio Noise Removal & Mastering', icon: '🎙️' },
      { name: 'Thumbnail Suggestions', icon: '🖼️' },
    ],
    published: true,
    sortOrder: 15,
  },
];

// Execute database update
db.services = enrichedServices;
writeDb(db);

console.log('✅ Services database successfully updated with streamlined 6-8 features per service and individual icons!');
